### ISSUE TITLE
feat: create structure for project

### ISSUE THREAD

**Issue by payam-zahedi** [PersianFlutter/website#2]
We need to create a structure for the project, and we need to take care of the following features: 

- [x] Folder structure
- [x] Routing structure
- [x] i18n 
- [x] i18n in navigation.ts file
- [x] Implement base Theme (styles) and add fonts

**Comment by alirezakariminejad** [comment]
Folder structure is complete.

**Comment by alirezakariminejad** [comment]
Routing structure

**Comment by alirezakariminejad** [comment]
Default i18n was created for Farsi and English language. Of course, when creating the components of the home page, we complete sour

**Comment by alirezakariminejad** [comment]
Implement base Theme (styles) and add fonts is complete

**Comment by alirezakariminejad** [comment]
Please pay attention to navigation.ts file in translations. 
Static items such as social networks, menu, etc. are placed in this, and items will be added to it in the future.

@payam-zahedi
